wip

diff --git a/build b/build
--- a/build
+++ b/build
@@ -92,148 +92,147 @@ mkdir -p ${BUILD_DIR}
 # feeds
 
 
+echo "Applying patches for OpenWRT base tree..."
+cd "${OPENWRT_CHECKOUT_DIR}"
+if [ ! -h "patches" ] ; then
+  ln -s "${workdir}/openwrt_patches" patches
+fi
+if [ ! -f "patches/series" ] ; then
+  quilt import patches/*
+fi
 
-# echo "Applying patches for OpenWRT base tree..."
-# cd "${OPENWRT_CHECKOUT_DIR}"
-# if [ ! -h "patches" ] ; then
-#   ln -s "${workdir}/openwrt_patches" patches
-# fi
-# if [ ! -f "patches/series" ] ; then
-#   quilt import patches/*
-# fi
-#
-# quilt push -f -a -q || [ $? -eq 2 ] #quilt returns a 2 if there is nothing more to do
-#
-# cd "${OPENWRT_CHECKOUT_DIR}"
-#
-# # Importing feeds
-# echo "Importing feeds"
-# ./scripts/feeds update -a > /dev/null
-#
-# for pkg in ${all_packages}; do
-#   # Check if package name begins with a minus
-#   if [[ ${pkg:0:1} != "-" ]]; then
-#     ./scripts/feeds install "${pkg}"
-#    fi
-# done
-#
-# # change back to initial directory
-# cd "${workdir}"
-#
-# openwrt_build_configure()
-# {
-#   local arch=$1
-#   local kconfig=${workdir}/${BUILD_DIR}/openwrt/scripts/kconfig.pl
-#   local config_dir=${workdir}/openwrt_config/arch_configs
-#   local config=${workdir}/${BUILD_DIR}/openwrt/config.${arch}
-#   $kconfig 'm+' "${config_dir}/generic" "${config_dir}/${arch}" > "${config}"
-#
-#   # Include all common packages
-#   for pkg in ${all_packages}; do
-#     # Check if package name begins with a minus
-#     if [[ ${pkg:0:1} == "-" ]]; then
-#       pkg=${pkg:1:${#pkg}-1} # strip first character
-#       echo "CONFIG_PACKAGE_${pkg}=n" >> "${config}"
-#     else
-#       echo "CONFIG_PACKAGE_${pkg}=y" >> "${config}"      
-#     fi
-#   done
-# }
-#
-# openwrt_buildprep()
-# {
-#   local arch=$1
-#   local build_dir=${workdir}/${BUILD_DIR}/builder.${arch}
-#
-#   # Make hardlinks to avoid space duplication but to still isolate builds
-#   cp -lr "${workdir}/${BUILD_DIR}/openwrt" "${build_dir}"
-#
-#   cp -r files "${build_dir}/"
-#
-#   local toolchain_dir_bin
-#   for file in ${build_dir}/staging_dir/*; do
-#     if [[ "${file}" == *"toolchain"* ]]; then
-#       toolchain_dir_bin="${file}/bin"
-#     fi
-#   done
-#   local staging_dir_bin=${build_dir}/staging_dir/host/bin
-#
-#   if grep -q "^export PATH=" ~/.bashrc
-#   then
-#     local path_line
-#     path_line=$(grep "^export PATH=" ~/.bashrc)
-#     path=${path_line#'export PATH='\'''}
-#     if [[ "${path}" != *"$staging_dir_bin"* ]]; then
-#       path=${staging_dir_bin}":"$path
-#     fi
-#
-#     if [[ "${path}" != *"$toolchain_dir_bin"* ]]; then
-#       path=${toolchain_dir_bin}":"$path
-#     fi
-#     sed -i "/export PATH=/c\export PATH='$PATH:${path}" ~/.bashrc
-#     # code if found
-#   else
-#     echo "export PATH='$PATH:${staging_dir_bin}:${toolchain_dir_bin}'" >> ~/.bashrc
-#   fi
-#
-#   # Prepare configuration file and build
-#   cd "${build_dir}"
-#   cp "config.${arch}" .config
-#   make defconfig V=s &> "${build_dir}/build.echo"
-#   if [ "$?" != "0" ]; then
-#     echo "Default configuration preparation for '${arch}' has failed. See build.echo for details!"
-#     exit 1
-#   fi
-# }
-#
-# openwrt_builder()
-# {
-#   local arch=$1
-#   local build_dir=${workdir}/${BUILD_DIR}/builder.${arch}
-#
-#   echo "Building ${arch} in dir: ${build_dir}"  
-#   make V=s -C "${build_dir}" 
-#   if [ "$?" != "0" ]; then
-#     echo "Build for architecture '${arch}' has failed. See ${build_dir}/build.log for details!"
-#     exit 1
-#   fi
-# }
-#
-# # Check if architecture is valid
-# all_architectures=$(cat openwrt_config/architectures)
-# for arch in $all_architectures; do
-#   if [[ "$architecture" == "$arch" ]]; then
-#     found=1
-#     break
-#   fi
-#
-#   if [ ! -d "${workdir}/${BUILD_DIR}/openwrt/target/linux/${arch}" ]; then
-#     echo "ERROR: OpenWRT itself does not support the architecture '${arch}'"
-#     exit 1
-#   fi
-#
-#   if [ ! -f "${workdir}/openwrt_config/arch_configs/${arch}" ]; then
-#     echo "ERROR: '${arch}' missing from openwrt_config/arch_configs/"
-#     exit 1
-#   fi
-# done
-#
-# if [[ $found == 0 ]]; then
-#   echo "ERROR: Invalid architecture '${arch}' specified."
-#   echo "  Architecture must be in openwrt_config/architectures"
-#   exit 1
-# fi
-#
-#
-# echo "Configuring build for the following OpenWRT packages:"
-#
-#
-# # Generate build configurations
-# echo "Generating build configurations..."
-# openwrt_build_configure "${architecture}"
-#
-# echo "Preparing for build"
-# openwrt_buildprep "${architecture}"
-#
-# echo "Building"
-# openwrt_builder "${architecture}"
+quilt push -f -a -q || [ $? -eq 2 ] #quilt returns a 2 if there is nothing more to do
+
+cd "${OPENWRT_CHECKOUT_DIR}"
+
+# Importing feeds
+echo "Importing feeds"
+./scripts/feeds update -a > /dev/null
+
+for pkg in ${all_packages}; do
+  # Check if package name begins with a minus
+  if [[ ${pkg:0:1} != "-" ]]; then
+    ./scripts/feeds install "${pkg}"
+   fi
+done
+
+# change back to initial directory
+cd "${workdir}"
+
+openwrt_build_configure()
+{
+  local arch=$1
+  local kconfig=${workdir}/${BUILD_DIR}/openwrt/scripts/kconfig.pl
+  local config_dir=${workdir}/openwrt_config/arch_configs
+  local config=${workdir}/${BUILD_DIR}/openwrt/config.${arch}
+  $kconfig 'm+' "${config_dir}/generic" "${config_dir}/${arch}" > "${config}"
+
+  # Include all common packages
+  for pkg in ${all_packages}; do
+    # Check if package name begins with a minus
+    if [[ ${pkg:0:1} == "-" ]]; then
+      pkg=${pkg:1:${#pkg}-1} # strip first character
+      echo "CONFIG_PACKAGE_${pkg}=n" >> "${config}"
+    else
+      echo "CONFIG_PACKAGE_${pkg}=y" >> "${config}"      
+    fi
+  done
+}
+
+openwrt_buildprep()
+{
+  local arch=$1
+  local build_dir=${workdir}/${BUILD_DIR}/builder.${arch}
+
+  # Make hardlinks to avoid space duplication but to still isolate builds
+  cp -lr "${workdir}/${BUILD_DIR}/openwrt" "${build_dir}"
+
+  cp -r files "${build_dir}/"
+
+  local toolchain_dir_bin
+  for file in ${build_dir}/staging_dir/*; do
+    if [[ "${file}" == *"toolchain"* ]]; then
+      toolchain_dir_bin="${file}/bin"
+    fi
+  done
+  local staging_dir_bin=${build_dir}/staging_dir/host/bin
+
+  if grep -q "^export PATH=" ~/.bashrc
+  then
+    local path_line
+    path_line=$(grep "^export PATH=" ~/.bashrc)
+    path=${path_line#'export PATH='\'''}
+    if [[ "${path}" != *"$staging_dir_bin"* ]]; then
+      path=${staging_dir_bin}":"$path
+    fi
+
+    if [[ "${path}" != *"$toolchain_dir_bin"* ]]; then
+      path=${toolchain_dir_bin}":"$path
+    fi
+    sed -i "/export PATH=/c\export PATH='$PATH:${path}" ~/.bashrc
+    # code if found
+  else
+    echo "export PATH='$PATH:${staging_dir_bin}:${toolchain_dir_bin}'" >> ~/.bashrc
+  fi
+
+  # Prepare configuration file and build
+  cd "${build_dir}"
+  cp "config.${arch}" .config
+  make defconfig V=s &> "${build_dir}/build.echo"
+  if [ "$?" != "0" ]; then
+    echo "Default configuration preparation for '${arch}' has failed. See build.echo for details!"
+    exit 1
+  fi
+}
+
+openwrt_builder()
+{
+  local arch=$1
+  local build_dir=${workdir}/${BUILD_DIR}/builder.${arch}
+
+  echo "Building ${arch} in dir: ${build_dir}"  
+  make V=s -C "${build_dir}" 
+  if [ "$?" != "0" ]; then
+    echo "Build for architecture '${arch}' has failed. See ${build_dir}/build.log for details!"
+    exit 1
+  fi
+}
+
+# Check if architecture is valid
+all_architectures=$(cat openwrt_config/architectures)
+for arch in $all_architectures; do
+  if [[ "$architecture" == "$arch" ]]; then
+    found=1
+    break
+  fi
+
+  if [ ! -d "${workdir}/${BUILD_DIR}/openwrt/target/linux/${arch}" ]; then
+    echo "ERROR: OpenWRT itself does not support the architecture '${arch}'"
+    exit 1
+  fi
+
+  if [ ! -f "${workdir}/openwrt_config/arch_configs/${arch}" ]; then
+    echo "ERROR: '${arch}' missing from openwrt_config/arch_configs/"
+    exit 1
+  fi
+done
+
+if [[ $found == 0 ]]; then
+  echo "ERROR: Invalid architecture '${arch}' specified."
+  echo "  Architecture must be in openwrt_config/architectures"
+  exit 1
+fi
+
+
+echo "Configuring build for the following OpenWRT packages:"
+
+
+# Generate build configurations
+echo "Generating build configurations..."
+openwrt_build_configure "${architecture}"
+
+echo "Preparing for build"
+openwrt_buildprep "${architecture}"
+
+echo "Building"
+openwrt_builder "${architecture}"
